# Generated by Django 3.2.8 on 2021-10-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='merchant',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('merchant_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(default='NOT_Recognized', max_length=15)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('current_queue_size', models.IntegerField()),
                ('approximate_queue_waiting_time', models.IntegerField()),
                ('waiting_time_per_person', models.FloatField()),
            ],
        ),
    ]
