# Generated by Django 3.2.8 on 2021-10-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognize', '0002_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='approximate_queue_waiting_time',
            field=models.IntegerField(default=0),
        ),
    ]
