# Generated by Django 3.2.8 on 2021-10-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognize', '0003_alter_merchant_approximate_queue_waiting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.CharField(default='Not_Registered', max_length=30),
        ),
    ]
